<a href="https://colab.research.google.com/github/Jarrod555/Linear-Algebra-Projects/blob/main/Gram_Schmidt_Orthonormalization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"



     

Vector operations for the Gram-Schmidt process

In [ ]:
#create a vector

In [ ]:
r1= np.array([1,2,3])
r1

array([1, 2, 3])

In [ ]:
#vector arithmetic#
-3* r1

array([-3, -6, -9])

In [ ]:
#vector dot product
r1.dot(r1)

14

In [ ]:
#magnitude
r1.size
r1.dot(r1)


14

In [ ]:
#need sqrt 
np.sqrt(14)

3.7416573867739413

In [ ]:
#magnitdue of vector r1
np.sqrt(r1.dot(r1))

3.7416573867739413

#Implement Gram-Schmidt on 4 vectors

In [ ]:
#orignal random vecotrs
r1= np.array([3,0,3,0])
r2= np.array([3,2,3,3])
r3= np.array([-7,-4,-5,-6])
r4= np.array([-7,-3,-11,2])


In [ ]:
print(r1)

[3 0 3 0]


In [ ]:
#process $r_1$
#choose the r1 one vector and subtract off orthogonal pieces


In [ ]:
t1=r1
t1

array([3, 0, 3, 0])

In [ ]:
#find the size of t1
M= np.sqrt(t1.dot(t1))
M

4.242640687119285

In [ ]:
#The nice vefctor is u1 = t1/m
u1=(1/M)*t1
u1

array([0.70710678, 0.        , 0.70710678, 0.        ])

In [ ]:
#verify the size is correct to check answer
(np.sqrt(u1.dot(u1)))

1.0

The size is 1


#Process $r_2$
additionally change the t1 and u1 to t2 and u2 etc.

```
`# This is formatted as code`
```



In [ ]:
t2=r2 - r2.dot(u1)*u1 # subtract orthogonal portion
t2

#find the size of t1
M= np.sqrt(t2.dot(t2))
M

#The nice vefctor is u2 = t2/m
u2=(1/M)*t2
u2


array([-1.23168186e-16,  5.54700196e-01, -1.23168186e-16,  8.32050294e-01])

In [ ]:
#verify the size is correct to check answer
print(np.sqrt(u1.dot(u1)))
print(np.sqrt(u2.dot(u2)))

print("u1 dotted with u2 =  ", u1.dot(u2))


1.0
1.0
u1 dotted with u2 =   -1.741861189847285e-16


In [ ]:
print(np.sqrt(u2.dot(u2)))
#process r3
t3=r3 - r3.dot(u1)*u1 - r3.dot(u2)*u2 # subtract orthogonal portion
t3

#find the size of t2
M= np.sqrt(t3.dot(t3))
M

#The nice vefctor is u3 = t3/m
u3=(1/M)*t3
u3

1.0


array([0.53881591, 0.3592106 , 0.53881591, 0.53881591])

In [ ]:
#verify the size is correct to check answer
print(np.sqrt(u1.dot(u1)))
print(np.sqrt(u2.dot(u2)))
print(np.sqrt(u3.dot(u3)))


print("u1 dotted with u2 =  ", u1.dot(u2))

print("u1 dotted with u3 =  ", u1.dot(u3))
print("u2 dotted with u3 =  ", u2.dot(u3))

1.0
1.0
1.0
u1 dotted with u2 =   -1.741861189847285e-16
u1 dotted with u3 =   0.7620007620011431
u2 dotted with u3 =   0.6475761258027332


In [ ]:
t4=r4 - r4.dot(u1)*r4 - r4.dot(u2)*r4 - r4.dot(u3)*r4  # subtract orthogonal portion
t4

#find the size of t4
M= np.sqrt(t4.dot(t4))
M

#The nice vector is u4 = t4/m
u4=(1/M)*t4
u4

array([-0.51745489, -0.22176638, -0.8131434 ,  0.14784425])

In [ ]:
#r1
#r2
#r3
#r4
print(r1.dot(u1), r1.dot(u2), r1.dot(u3), r1.dot(u4)) 
print(r2.dot(u1) ,  r2.dot(u2) , r2.dot(u3) , r2.dot(u4))
print(r3.dot(u1), r3.dot(u2), r3.dot(u3), r3.dot(u4))
print(r4.dot(u1), r4.dot(u2), r4.dot(u3), r4.dot(u4))

4.242640687119286 -3.2328954364819475 3.2145995037318977 -3.991794863154693
4.242640687119286 -5.567764362830021 5.536254700871602 -3.991794863154693
-8.485281374238571 11.135528725660041 -11.222753050543988 7.687901217927557
-12.727922061357855 9.698686309445844 -9.343311213594124 13.527749258468683


In [ ]:
#square the values above after correcting the r1 instead of u1 factor of multiplication to express the vector rn as some combination of all of the uhat vectors where the scalar value is the square root of the square of the values
