<a href="https://colab.research.google.com/github/Jarrod555/Linear-Algerbra-Projects/blob/main/Take_Home_Exam_1_Drug_Markov_Chain_Problem_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from numpy import c_

ll = "loaded"




In [3]:
# create the matrix M:
M = np.matrix([[4/10,1/2,1/5,0],
               [3/10,0,2/5,0],
               [3/10,0,2/5,0],
               [0,1/2,0,1]])
M

matrix([[0.4, 0.5, 0.2, 0. ],
        [0.3, 0. , 0.4, 0. ],
        [0.3, 0. , 0.4, 0. ],
        [0. , 0.5, 0. , 1. ]])

In [4]:
x0 = np.matrix([[100], [200], [0], [0]])
x0

matrix([[100],
        [200],
        [  0],
        [  0]])

In [5]:
x1 = M*x0
x2 = M*x1
(M**3)*x0

matrix([[ 68.6],
        [ 44.7],
        [ 44.7],
        [142. ]])

In [7]:
(M**2)*x0

matrix([[ 77.],
        [ 54.],
        [ 54.],
        [115.]])

In [8]:
(M**4)*x0

matrix([[ 58.73],
        [ 38.46],
        [ 38.46],
        [164.35]])

In [9]:
(M**48)*x0

matrix([[7.04863641e-02],
        [4.61441570e-02],
        [4.61441570e-02],
        [2.99837225e+02]])